project:
  type: website

website:
  title: "Thème 4 - Centre de ressources"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: "theme-4-partie-1-cua.qmd"
        text: CUA
      - href: "theme-4-partie-2-pser.qmd"
        text: PSE·R
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



